### ISSUE TITLE
Sliding Tabs

### ISSUE THREAD

**Issue by Luviro** [YahyaAAAAAAA/DrawOverIt#1]
https://github.com/user-attachments/assets/0b83b121-af27-421f-8bba-473f3183d1ab

can you make the floating board and "draw over it" tab match the mouse speed and not slide

**Comment by YahyaAAAAAAA** [comment]
I have published a new version with your desired feature, plese check it out and let me know if you need anything else.
https://github.com/YahyaAAAAAAA/DrawOverIt/releases/tag/v2.0
